import { ButtonWebComponent } from "./components/button/button.component";
import { TextfieldWebComponent } from "./components/textflied/textfield.component";
import { EmergencyloginWebComponent } from "./modules/login/emergencylogin.component";
import { RegistroWebComponent } from "./components/registro/registro.component";
import { DropdownWebComponent } from "./components/dropdown/dropdown.component";
import { ResultbillcreationWebComponent } from "./modules/resultbillcreation/resultbillcreation.component";
import { LabelWebComponent } from "./components/label/label.component";
import { CalendarWebComponent } from "./components/caledar/calendar.component";
import { CreatereservationWebComponent } from "./modules/createreservation/createreservation.component";
import './../style/facturero.global.scss';
